name: Run tests against Sudoku puzzle solver

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run_javascript_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm test --ci --coverage && ./node_modules/codecov/bin/codecov -t ${{ secrets.CODECOV_TOKEN }}
  run_go_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1'
      - run: npm ci # to get codecov in this container
      - run: go test -v && ./node_modules/codecov/bin/codecov -t ${{ secrets.CODECOV_TOKEN }}
