name: Run tests against Sudoku puzzle solver

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run_javascript_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm run test:make-badges
      - run: mv .badges/badge-statements.svg suduko-statement-coverage.svg
      - run: curl --location --request POST 'https://uzhf08x6h3.execute-api.eu-west-2.amazonaws.com/test/upload' --form 'file=@"./suduko-statement-coverage.svg"'
  run_go_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1'
      - run: go test
      - run: go get github.com/jpoles1/gopherbadger && gopherbadger
      - run: mv coverage_badge.png suduko_coverage.png
      - run: curl --location --request POST 'https://uzhf08x6h3.execute-api.eu-west-2.amazonaws.com/test/upload' --form 'file=@"./suduko_coverage.png"'
